
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: debug-statements

- repo: https://github.com/PyCQA/isort
  rev: "7.0.0"
  hooks:
  - id: isort
    args: []
    additional_dependencies: [toml]
    exclude: docs/tutorials

- repo: https://github.com/psf/black-pre-commit-mirror
  rev: "25.9.0"
  hooks:
    - id: black
    - id: black-jupyter
